# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"mult2": "00_core.ipynb",
         "mult3": "example_notebook.ipynb",
         "hello_world": "01_nbdev_try.ipynb",
         "div2": "01_run_analysis.ipynb",
         "cube": "01_run_analysis.ipynb",
         "a_working_function": "01_something_different_than_that.ipynb",
         "this_thing": "all_flags_test.ipynb",
         "mult5": "load_files.ipynb"}

modules = ["core.py",
           "stuff.py",
           "nbdev_try.py",
           "run_analysis.py",
           "something_else.py",
           "all_flags_test.py",
           "example_notebook.py",
           "load_files.py"]

doc_url = "https://vanderbilt-data-science.github.io/nbdev_playground/"

git_url = "https://github.com/vanderbilt-data-science/nbdev_playground/tree/master/"

def custom_doc_links(name): return None
