# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"mult2": "00_core.ipynb",
         "sarah": "sarah_test.ipynb"}

modules = ["core.py",
           "sarah_test.py"]

doc_url = "https://vanderbilt-data-science.github.io/nbdev_playground/"

git_url = "https://github.com/vanderbilt-data-science/nbdev_playground/tree/master/"

def custom_doc_links(name): return None
