# AUTOGENERATED! DO NOT EDIT! File to edit: .ipynb_checkpoints/all_flags_test-checkpoint.ipynb (unless otherwise specified).

__all__ = ['this_thing', 'this_thing']

# Cell
def this_thing(that):
    return (that + 5)

# Cell
def this_thing(that):
    return (that + 5)