# AUTOGENERATED! DO NOT EDIT! File to edit: .ipynb_checkpoints/00_core-checkpoint.ipynb (unless otherwise specified).

__all__ = ['add_one', 'mult2', 'add_one', 'mult2']

# Cell
def add_one(val):
    print(val)
    return val + 1

# Cell
def mult2(voi):
    '''This function multiples an input by two.
    voi: numerical (int, float)
    returns: voi*2
    '''

    return voi*2

# Cell
def add_one(val):
    print(val)
    return val + 1

# Cell
def mult2(voi):
    '''This function multiples an input by two.
    voi: numerical (int, float)
    returns: voi*2
    '''

    return voi*2