# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['mult2']

# Cell
def mult2(voi):
    '''This function multiples an input by two.
    voi: numerical (int, float)
    returns: voi*2
    '''

    return voi*2