# AUTOGENERATED! DO NOT EDIT! File to edit: .ipynb_checkpoints/load_files-checkpoint.ipynb (unless otherwise specified).

__all__ = ['mult5', 'mult5']

# Cell
def mult5(voi):
    return voi*5

# Cell
def mult5(voi):
    return voi*5