# AUTOGENERATED! DO NOT EDIT! File to edit: .ipynb_checkpoints/01_nbdev_try-checkpoint.ipynb (unless otherwise specified).

__all__ = ['hello_world', 'hello_world']

# Cell
def hello_world(a):
    '''This function multiples an input by two.
    voi: numerical (int, float)
    returns: voi*2
    '''

    return 100

# Cell
def hello_world(a):
    '''This function multiples an input by two.
    voi: numerical (int, float)
    returns: voi*2
    '''

    return 100