# AUTOGENERATED! DO NOT EDIT! File to edit: .ipynb_checkpoints/01_run_analysis-checkpoint.ipynb (unless otherwise specified).

__all__ = ['div2', 'div2']

# Cell
def div2(voi):
    '''This function divides an input by two.
    voi: numerical (int, float)
    returns: voi/2
    '''

    return voi/2

# Cell
def div2(voi):
    '''This function divides an input by two.
    voi: numerical (int, float)
    returns: voi/2
    '''

    return voi/2