# AUTOGENERATED! DO NOT EDIT! File to edit: 01_run_analysis.ipynb (unless otherwise specified).

__all__ = ['div2', 'cube']

# Cell
def div2(voi):
    '''This function divides an input by two.
    voi: numerical (int, float)
    returns: voi/2
    '''

    return voi/2

# Cell
def cube(x):
    #cubing the input, x
    final = x*x*x
    return final