# AUTOGENERATED! DO NOT EDIT! File to edit: 01_something_different_than_that.ipynb (unless otherwise specified).

__all__ = ['a_working_function']

# Cell
def a_working_function(voi):
    '''This function multiples an input by two.
    voi: numerical (int, float)
    returns: voi*2
    '''

    return 'a working function'