# AUTOGENERATED! DO NOT EDIT! File to edit: 01_do_stuff.ipynb (unless otherwise specified).

__all__ = ['mult3']

# Cell
def mult3(voi):
    '''This function multiples an input by two.
    voi: numerical (int, float)
    returns: voi*2
    '''

    return voi*3